#bash reward_modeling/train_compact_reward_model.sh
#bash reward_modeling/rpe_train_fact_rm_longformer_compact.sh
#bash reward_modeling/rpe_train_fact_rm_llama3.sh
#bash reward_modeling/rpe_train_fact_rm_longformer.sh
#bash reward_modeling/rpe_train_fact_rm_longformer_sixinone.sh
bash reward_modeling/rpe_train_fact_rm_longformer_cg-prm.sh


